src/ShapeApp/ShapeApp/Controllers/PerfilController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShapeApp.Models;

namespace ShapeApp.Controllers
{
    [Authorize]
    public class PerfilController : Controller
    {
        private readonly AppDbContext _context;

        public PerfilController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Perfil
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                int? id = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);

                if (id == null || _context.Usuarios == null)
                {
                    return NotFound();
                }

                var usuario = await _context.Usuarios.FindAsync(id);
                if (usuario == null)
                {
                    return NotFound();
                }

                var perfilShape = await _context.PerfilShape.FindAsync(id);
                if (perfilShape == null)
                {
                    return NotFound();
                }

                var dadosCadastro = new DadosCadastro
                {
                    Usuario = usuario,
                    PerfilShape = perfilShape
                };

                return View(dadosCadastro);
            }
            else
            {
                return BadRequest();
            }
        }

        // POST: Perfil
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Usuario,PerfilShape")] DadosCadastro dadosCadastro)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    dadosCadastro.Usuario.Senha = BCrypt.Net.BCrypt.HashPassword(dadosCadastro.Usuario.Senha);
                    _context.Usuarios.Update(dadosCadastro.Usuario);
                    await _context.SaveChangesAsync();

                    dadosCadastro.PerfilShape.IdPerfil = dadosCadastro.Usuario.Id;
                    dadosCadastro.PerfilShape.UsuarioId = dadosCadastro.Usuario.Id;
                    _context.PerfilShape.Update(dadosCadastro.PerfilShape);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(dadosCadastro.Usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("/");
            }
            return View(dadosCadastro);
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }

    }
}

src/ShapeApp/ShapeApp/Controllers/TreinosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShapeApp.Models;

namespace ShapeApp.Controllers
{
    [Authorize]
    public class TreinosController : Controller
    {
        private readonly AppDbContext _context;
        public TreinosController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var dados = await _context.Treinos
                .Include(treino => treino.Exercicios)
                .ToListAsync();

            return View(dados);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Treino treino)
        {
            if (ModelState.IsValid)
            {
                var exercicios = await _context.Exercicios.ToListAsync();

                var quantidade = new Random().Next(Math.Min(4, exercicios.Count), exercicios.Count);

                for (int i = 0; i < quantidade; i++)
                {
                    var exercicio = exercicios[new Random().Next(0, exercicios.Count)];
                    treino.Exercicios.Add(exercicio);
                }

                _context.Treinos.Add(treino);


                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(treino);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();
            var dados = await _context.Treinos.FindAsync(id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Treino treino)
        {
            if (id != treino.Id)
                return NotFound(id);

            if (ModelState.IsValid)
            {
                _context.Treinos.Update(treino);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Treinos.FindAsync(id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Treinos.FindAsync(id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Treinos.FindAsync(id);

            if (dados == null)
                return NotFound();

            _context.Treinos.Remove(dados);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Exercicios(int? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Treinos.Include(t => t.Exercicios).FirstOrDefaultAsync(t => t.Id == id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }

        public async Task<IActionResult> RemoverExercicio(int id, int exericioid)
        {
            // Busca o Treino com o ID
            var dados = await _context.Treinos.Include(t => t.Exercicios).FirstOrDefaultAsync(t => t.Id == id);

            // Busca o Exericio dentro do treino ID cujo exercicio seja o exericicioid
            var exericio = dados.Exercicios.FirstOrDefault(e => e.Id == exericioid);

            // remove o exercicio da lista para aquele treino ID
            dados.Exercicios.Remove(exericio);

            await _context.SaveChangesAsync();

            return RedirectToAction("Exercicios", new { id = id });
        }

        public async Task<IActionResult> AddExercicio(int? id)
        {
            var dados = await _context.Treinos.Include(t => t.Exercicios).FirstOrDefaultAsync(t => t.Id == id);

            // Lista todos os exercícios
            var exercicios = await _context.Exercicios.ToListAsync();

            ViewBag.Exercicios = exercicios;

            return View(dados);
        }

        public async Task<IActionResult> VincularExercicio(int id, int exercicioId)
        {

            var exercicio = await _context.Exercicios.FindAsync(exercicioId);

            var treino = await _context.Treinos.Include(t => t.Exercicios).FirstOrDefaultAsync(t => t.Id == id);

            treino.Exercicios.Add(exercicio);

            await _context.SaveChangesAsync();

            return RedirectToAction("Exercicios", new { id = id });
        }
    }
}

src/ShapeApp/ShapeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ShapeApp</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ShapeApp.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img style="width: 100px" src="~/logo-shapeapp-menu.png" /></a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Perfil" asp-action="Index">Perfil</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Treinos" asp-action="Index">Meus Treinos</a>
						</li>
						@*                         
						<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Frequencia" asp-action="Index">Frequência na Academia</a>
						</li>

						<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Compartilhamento" asp-action="Index">Compartilhamento</a>
						</li> *@

						@if (User.IsInRole("Admin"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Exercicios" asp-action="Index">Exercícios</a>
							</li>
						}

					</ul>
					<ul class="navbar-nav">

						@if (User.Identity.IsAuthenticated)
						{
							<li class="nav-item">
								Olá, @User.Identity.Name <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Sair</a>
							</li>
						}
						else
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Login">Login</a>
							</li>
						}

				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - ShapeApp
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>